# Generated by Django 4.2.3 on 2023-07-09 10:48

import apps.Fruitipedia.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), apps.Fruitipedia.models.use_leters_only], verbose_name='Name')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('nutrition', models.TextField(verbose_name='Nutrition')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), apps.Fruitipedia.models.first_letter_must_be_alpha], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), apps.Fruitipedia.models.first_letter_must_be_alpha], verbose_name='Last Name')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Password')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('age', models.IntegerField(blank=True, default=18, verbose_name='Age')),
            ],
        ),
    ]
