# Generated by Django 5.0.4 on 2024-04-17 06:16

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[app.models.validate_nickname], verbose_name='Nickname')),
                ('first_name', models.CharField(max_length=30, validators=[app.models.validate_name_start_with_capital], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[app.models.validate_name_start_with_capital], verbose_name='Last Name')),
                ('chef', models.BooleanField(default=False, verbose_name='Chef')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Title')),
                ('cuisine_type', models.CharField(choices=[('French', 'French'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Balkan', 'Balkan'), ('Other', 'Other')], max_length=7, verbose_name='Cuisine Type')),
                ('ingredients', models.TextField(help_text='Ingredients must be separated by a comma and space.', verbose_name='Ingredients')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('cooking_time', models.PositiveIntegerField(help_text='Provide the cooking time in minutes.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cooking Time')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
            ],
        ),
    ]
