# Generated by Django 4.2.4 on 2023-08-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarCollection_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='emails',
            new_name='email',
        ),
    ]
