# Generated by Django 4.2.4 on 2023-08-15 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCollection_App', '0002_rename_emails_profilemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price'),
        ),
    ]
