# Generated by Django 5.0.4 on 2024-04-17 03:52

import ExamPrep3.exm.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[ExamPrep3.exm.models.validate_username], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('age', models.IntegerField(help_text='Age requirement: 21 years and above', verbose_name='Age')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Last Name')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Rally', 'Rally'), ('Open-wheel', 'Open-wheel'), ('Kart', 'Kart'), ('Drag', 'Drag'), ('Other', 'Other')], max_length=10, verbose_name='Type')),
                ('model', models.CharField(max_length=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Model')),
                ('year', models.IntegerField(validators=[ExamPrep3.exm.models.validate_year], verbose_name='Year')),
                ('image_url', models.URLField(default='https://...', unique=True, validators=[ExamPrep3.exm.models.validate_unique_image_url], verbose_name='Image URL')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Price')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='exm.profile', verbose_name='Owner')),
            ],
        ),
    ]
