# Generated by Django 5.0.4 on 2024-04-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=15, verbose_name='Model'),
        ),
    ]
