name: Testing and Deploying WEB App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit_tests:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Run npm install
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display my SoftUni Username
      run: echo "KristiyqnPisev"
  

  build_ui_tests:
      runs-on: ubuntu-latest
      needs: build_unit_tests

      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Run npm install
        run: npm install
      - name: Install playwright brousers
        run: npx playwright install
      - name: Start the app
        run: npm run start &
      - name: Run ui tests
        run: npm run test:ui


  deploy:
    runs-on: ubuntu-latest
    needs: build_ui_tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
