# Generated by Django 4.2.3 on 2023-08-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieHaven_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
