# Generated by Django 4.2.3 on 2023-08-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieHaven_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
