# Generated by Django 4.2.3 on 2023-08-09 12:35

import apps.FoodieHaven_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieHaven_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='username',
            field=models.CharField(unique=True, validators=[apps.FoodieHaven_app.models.no_spaces], verbose_name='Username'),
        ),
    ]
