# Generated by Django 4.2.3 on 2023-08-09 04:50

import apps.FoodieHaven_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieHaven_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='title',
            field=models.CharField(max_length=20, validators=[apps.FoodieHaven_app.models.validate_unique_title], verbose_name='Recipe Title'),
        ),
    ]
