# Generated by Django 5.0.4 on 2024-04-16 14:19

import ExamPrep2.webapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, unique=True, verbose_name='Album Name')),
                ('artist', models.CharField(max_length=30, verbose_name='Artist')),
                ('genre', models.CharField(choices=[('pop', 'Pop Music'), ('jazz', 'Jazz Music'), ('rnb', 'R&B Music'), ('rock', 'Rock Music'), ('country', 'Country Music'), ('dance', 'Dance Music'), ('hiphop', 'Hip Hop Music'), ('other', 'Other')], max_length=30, verbose_name='Genre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('imageURL', models.URLField(verbose_name='image URL')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), ExamPrep2.webapp.models.letters_numbers_underscores_only_validator], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
            ],
        ),
    ]
